name: g12
description: A fitness habit APP.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.10.0
  firebase_database: ^10.1.1
  firebase_auth: ^4.4.1
  path: ^1.8.2
  table_calendar: ^3.0.8
  intl: ^0.17.0
  video_player: ^2.6.0
  flutter_heatmap_calendar: ^1.0.5
  step_progress_indicator: ^1.0.2
  motion_toast: ^2.6.8
  babstrap_settings_screen: ^0.1.5+1
  flutter_pin_code_fields: ^2.2.0
  onscreen_num_keyboard: ^1.0.4
  flutter_snake_navigationbar: ^0.6.1
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.1.0
  level_map: ^0.2.0
  google_fonts: ^4.0.3
  percent_indicator: ^4.0.1
  banner_carousel: ^1.2.1
  chat_bubbles: ^1.3.0
  swipe_cards: ^2.0.0+1
  font_awesome_flutter: ^9.2.0
  animations: 2.0.7
  animated_text_kit: ^4.2.2
  datepicker_cupertino: ^0.0.4
  square_progress_bar: ^1.1.1
  dots_indicator: ^3.0.0
  toggle_switch: ^2.1.0
  flutter_easyloading: ^3.0.5
  loading_animation_widget: ^1.2.0
  syncfusion_flutter_charts: ^21.2.4
  awesome_dialog: ^3.1.0
  scroll_date_picker: ^3.7.3
  assorted_layout_widgets: ^8.0.4
  flutter_rating_bar: ^4.0.1
  roundcheckbox: ^2.0.5
  multi_select_flutter: ^4.1.3
  flutter_local_notifications: ^15.1.1
  provider: ^5.0.0
  flutter_datetime_picker: ^1.5.1
  timezone: ^0.9.2
  flutter_native_timezone: ^2.0.0
  carousel_slider: ^4.2.1
  collection: ^1.17.0
  fl_chart: ^0.35.0
  speech_balloon: ^0.0.4
  confetti: ^0.7.0
  permission_handler: ^11.0.1
  showcaseview: ^2.0.3
  page_view_dot_indicator: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
flutter_icons:
  android: false
  ios: true
  image_path: "assets/images/AppIcon.png"
  # https://www.flutterbeads.com/change-app-launcher-icon-flutter/

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/videos/v1.gif
    - assets/videos/v2.gif
    - assets/videos/v3.gif
    - assets/videos/深蹲.gif
    - assets/videos/側弓箭步.gif
    - assets/videos/上斜伏地挺身.gif
    - assets/videos/反向捲腹.gif
    - assets/videos/臀橋.gif
    - assets/videos/休息.gif
    - assets/videos/冥想.gif
    - assets/images/testPic.gif
    - assets/images/Logo.png
    - assets/images/lazy.png
    - assets/images/LINE.jpg
    - assets/images/finish.png
    - assets/images/visa.png
    - assets/images/mastercard.png
    - assets/images/jcb.png
    - assets/images/finish.png
    - assets/images/Exercise_1.jpg
    - assets/images/Exercise_2.jpg
    - assets/images/Meditation_1.jpg
    - assets/images/Meditation_2.png
    - assets/images/Rest.PNG

   # 兔子
    - assets/images/Rabbit_1.png
    - assets/images/Rabbit_2.png
    - assets/images/Rabbit_head.png
    - assets/images/Rabbit_shining.png
    - assets/images/Rabbit_sad.png
    - assets/images/Contract.gif
    - assets/images/coming_soon.png

   # 八種人格角色 (正常)
    - assets/images/Dog_1.png
    - assets/images/Dog_2.png
    - assets/images/Fox_1.png
    - assets/images/Fox_2.png
    - assets/images/Lion_1.png
    - assets/images/Lion_2.png
    - assets/images/Sheep_1.png
    - assets/images/Sheep_2.png
    - assets/images/Sloth_1.png
    - assets/images/Sloth_2.png
    - assets/images/Mouse_1.png
    - assets/images/Mouse_2.png
    - assets/images/Cat_1.png
    - assets/images/Cat_2.png
    - assets/images/Pig_1.png
    - assets/images/Pig_2.png
   # 八種人格角色 (黑影)
    - assets/images/Dog_2_black.png
    - assets/images/Fox_2_black.png
    - assets/images/Lion_2_black.png
    - assets/images/Sheep_2_black.png
    - assets/images/Sloth_2_black.png
    - assets/images/Mouse_2_black.png
    - assets/images/Cat_2_black.png
    - assets/images/Pig_2_black.png
    - assets/images/Mouse_3_black.png
   # 八種人格角色 (頭貼)
    - assets/images/Dog_1_head.png
    - assets/images/Dog_2_head.png
    - assets/images/Fox_1_head.png
    - assets/images/Fox_2_head.png
    - assets/images/Lion_1_head.png
    - assets/images/Lion_2_head.png
    - assets/images/Sheep_1_head.png
    - assets/images/Sheep_2_head.png
    - assets/images/Sloth_1_head.png
    - assets/images/Sloth_2_head.png
    - assets/images/Mouse_1_head.png
    - assets/images/Mouse_2_head.png
    - assets/images/Cat_1_head.png
    - assets/images/Cat_2_head.png
    - assets/images/Pig_1_head.png
    - assets/images/Pig_2_head.png

   # 冥寶、運寶 (正常)
    - assets/images/Carrot.png
    - assets/images/BowTie.png
    - assets/images/Dog_workoutGem.png
    - assets/images/Dog_meditationGem.png
    - assets/images/Fox_workoutGem.png
    - assets/images/Fox_meditationGem.png
    - assets/images/Lion_workoutGem.png
    - assets/images/Lion_meditationGem.png
    - assets/images/Sheep_workoutGem.png
    - assets/images/Sheep_meditationGem.png
    - assets/images/Sloth_workoutGem.png
    - assets/images/Sloth_meditationGem.png
    - assets/images/Mouse_workoutGem.png
    - assets/images/Mouse_meditationGem.png
    - assets/images/Cat_workoutGem.png
    - assets/images/Cat_meditationGem.png
    - assets/images/Pig_workoutGem.png
    - assets/images/Pig_meditationGem.png
   # 冥寶、運寶 (黑影)
    - assets/images/Dog_workoutGem_black.png
    - assets/images/Dog_meditationGem_black.png
    - assets/images/Fox_workoutGem_black.png
    - assets/images/Fox_meditationGem_black.png
    - assets/images/Lion_workoutGem_black.png
    - assets/images/Lion_meditationGem_black.png
    - assets/images/Sheep_workoutGem_black.png
    - assets/images/Sheep_meditationGem_black.png
    - assets/images/Sloth_workoutGem_black.png
    - assets/images/Sloth_meditationGem_black.png
    - assets/images/Mouse_workoutGem_black.png
    - assets/images/Mouse_meditationGem_black.png
    - assets/images/Cat_workoutGem_black.png
    - assets/images/Cat_meditationGem_black.png
    - assets/images/Pig_workoutGem_black.png
    - assets/images/Pig_meditationGem_black.png

    # To add assets to your application, add an assets section, like this:
    # assets:
    #   - images/a_dot_burr.jpeg
    #   - images/a_dot_ham.jpeg

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#fdependencies:
    #  table_calendar: ^3.0.9rom-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages